[package]
name = "chess_position_trainer"
version = "0.1.0"
authors = ["Laurent Bernabe <laurent.bernabe@gmail.com>"]
license = "MIT"

[dependencies]
cairo-rs = "0.5.0"

[dependencies.gtk]
version = "0.5.0"
features = ["v3_10"]